# Generated by Django 5.0.1 on 2024-02-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='content',
            new_name='text',
        ),
    ]
