# Generated by Django 5.0.1 on 2024-02-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsapp', '0002_rename_content_sentence_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sentence',
        ),
    ]
