# Generated by Django 5.0.1 on 2024-02-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsapp', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='score',
            field=models.IntegerField(),
        ),
    ]
